project_id = "xtftehtsfnxsdsfmwkew"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-transactional-email]
    verify_jwt = false
  [functions.send-reminders]
    verify_jwt = true
  [functions.invite-client]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.calendly-webhook]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.stripe-portal]
    verify_jwt = false
  [functions.sync-outlook-calendar]
    verify_jwt = false
  [functions.push-outlook-event]
    verify_jwt = false
